In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.dates as mdates
import matplotlib.colors as mcolors
import difflib

# Data Exploration 2023

## Read CSVs

In [ ]:
caract_2023 = pd.read_csv("caract-2023.csv",encoding="utf-8",sep=";")
lieux_2023 = pd.read_csv("lieux-2023.csv",encoding="utf-8",sep=";")
usagers_2023 = pd.read_csv("usagers-2023.csv",encoding="utf-8",sep=";")
vehicules_2023 = pd.read_csv("vehicules-2023.csv",encoding="utf-8",sep=";")

C:\Users\guscr\AppData\Local\Temp\ipykernel_46812\872117635.py:3: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  lieux_2023 = pd.read_csv("lieux-2023.csv",encoding="utf-8",sep=";")

### Characteristics

In [46]:
display(caract_2023.head(20))
print()
print(caract_2023.info())
print()
print(caract_2023.describe())
print()
print(caract_2023.nunique())
print()
print(caract_2023['lum'].value_counts())
print()
print(caract_2023['agg'].value_counts())
print()
print(caract_2023['int'].value_counts())
print()
print(caract_2023['atm'].value_counts())
print()
print(caract_2023['col'].value_counts())

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202300000001,7,5,2023,06:00,1,75,75101,2,4,2,7,RUE DE RIVOLI,"48,86638600","2,32347100"
1,202300000002,7,5,2023,05:30,5,94,94080,2,1,3,6,Avenue de Paris,"48,84547782","2,42868146"
2,202300000003,7,5,2023,20:50,1,94,94022,2,3,2,1,Avenue du Général Leclerc,"48,76240000","2,40655000"
3,202300000004,6,5,2023,23:57,5,94,94078,2,1,3,5,Rue de Paris,"48,73248432","2,44687575"
4,202300000005,7,5,2023,00:50,5,94,94068,2,2,3,3,56bis Avenue Raspail,"48,78581000","2,49217000"
5,202300000006,7,5,2023,18:10,1,94,94058,2,3,2,6,Avenue Gabriel Péri,"48,83717000","2,51361000"
6,202300000007,7,5,2023,18:45,1,94,94076,2,1,2,4,185 Boulevard Maxime Gorki,"48,78693219","2,36756095"
7,202300000008,7,5,2023,17:20,1,94,94011,2,2,3,1,Route de Stains / Rue du Moulin Bateau,"48,78238000","2,49510000"
8,202300000009,7,5,2023,18:50,1,94,94022,2,3,8,3,Avenue de la République,"48,76240184","2,40690601"
9,202300000010,7,5,2023,18:20,1,94,94079,2,1,2,6,Boulevard de Friedberg,"48,83266000","2,54378000"
10,202300000011,7,5,2023,12:15,1,95,95527,1,9,2,3,A3,"48,99572240","2,51560628"
11,202300000012,6,5,2023,11:15,1,93,93051,2,3,8,3,Rue du Docteur Vaillant / A4,"48,83611000","2,56460000"
12,202300000013,7,5,2023,20:10,1,93,93030,2,1,2,2,Avenue Ambroise Croizat,"48,95859534","2,41581470"
13,202300000014,7,5,2023,10:30,1,93,93013,2,6,1,6,Carrefour Lindbergh,"48,94211000","2,42916000"
14,202300000015,7,5,2023,19:15,1,93,93010,2,1,2,2,Avenue Galliéni,"48,90631671","2,48228681"
15,202300000016,7,5,2023,01:56,5,92,92050,2,2,3,3,CLEMENCEAU GEORGES AVENUE N° PAIR,"48,88677185","2,20519647"
16,202300000017,7,5,2023,21:40,5,92,92007,2,9,2,3,VERDUN (RUE DE) N° PAIRS,"48,80202300","2,31800600"
17,202300000018,7,5,2023,12:10,1,01,01383,1,3,3,1,D1083,"46,08672900","5,11126600"
18,202300000019,8,5,2023,12:35,1,38,38378,2,1,1,6,"Route de condrieu, D4","45,43994100","4,76989000"
19,202300000020,8,5,2023,15:10,1,91,91022,1,1,1,1,Arrancourt,"48,33290200","2,14722600"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54822 entries, 0 to 54821
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  54822 non-null  int64
 1   jour     54822 non-null  int64
 2   mois     54822 non-null  int64
 3   an       54822 non-null  int64
 4   hrmn     54822 non-null  object
 5   lum      54822 non-null  int64
 6   dep      54822 non-null  object
 7   com      54822 non-null  object
 8   agg      54822 non-null  int64
 9   int      54822 non-null  int64
 10  atm      54822 non-null  int64
 11  col      54822 non-null  int64
 12  adr      53433 non-null  object
 13  lat      54822 non-null  object
 14  long     54822 non-null  object
dtypes: int64(9), object(6)
memory usage: 6.3+ MB
None

            Num_Acc          jour          mois       an           lum  \
count  5.482200e+04  54822.000000  54822.000000  54822.0  54822.000000
mean   2.023000e+11     15.396629      6.744628   2023.0      1.937653
std    1.582589e+04      8.705039      3.368853      0.0      1.485124
min    2.023000e+11      1.000000      1.000000   2023.0     -1.000000
25%    2.023000e+11      8.000000      4.000000   2023.0      1.000000
50%    2.023000e+11     15.000000      7.000000   2023.0      1.000000
75%    2.023000e+11     23.000000     10.000000   2023.0      3.000000
max    2.023001e+11     31.000000     12.000000   2023.0      5.000000

                agg           int           atm           col
count  54822.000000  54822.000000  54822.000000  54822.000000
mean       1.626135      2.085167      1.636296      4.034129
std        0.483833      2.022823      1.692539      1.973341
min        1.000000     -1.000000     -1.000000     -1.000000
25%        1.000000      1.000000      1.000000      3.000000
50%        2.000000      1.000000      1.000000      3.000000
75%        2.000000      2.000000      1.000000      6.000000
max        2.000000      9.000000      9.000000      7.000000

Num_Acc    54822
jour          31
mois          12
an             1
hrmn        1409
lum            6
dep          107
com        11311
agg            2
int           10
atm           10
col            8
adr        29080
lat        52905
long       53148
dtype: int64

lum
 1    36117
 5     8498
 3     5913
 2     3643
 4      649
-1        2
Name: count, dtype: int64

agg
2    34326
1    20496
Name: count, dtype: int64

int
 1    34842
 2     6743
 3     6359
 9     2489
 6     2440
 4     1095
 7      415
 5      292
 8      141
-1        6
Name: count, dtype: int64

atm
 1    42747
 2     6630
 8     2233
 3     1505
 7      954
 5      239
 9      208
 6      185
 4      117
-1        4
Name: count, dtype: int64

col
 6    16625
 3    16376
 2     7269
 1     5873
 7     5198
 4     1843
 5     1625
-1       13
Name: count, dtype: int64

Lighting conditions at accident time (lum): most of the accidents occurred during daylight (1)
Localisation (Agg): Most accidents occurred in urban areas (2)
Type of Intersection (Int): Most accidents occurred not at intersections (1)
Meteorological factors (atm): Most accidents occurred in normal weather (1)

### Places

In [43]:
display(lieux_2023.head(15))
print()
print(lieux_2023.info())
print()
print(lieux_2023.describe())
print()
print(lieux_2023.nunique())
print()
print(lieux_2023['catr'].value_counts())
print()
print(lieux_2023['voie'].value_counts())
print()
print(lieux_2023['circ'].value_counts())
print()
print(lieux_2023['nbv'].value_counts())
print()
print(lieux_2023['surf'].value_counts())
print()
print(lieux_2023['situ'].value_counts())
print()
print(lieux_2023['vma'].value_counts())

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202300000001,4,RUE DE RIVOLI,0,NaN,1,2,0,1,-1,-1,1,NaN,-1,2,0,1,30
1,202300000001,4,RUE SAINT FLORENTIN,0,NaN,1,1,0,1,-1,-1,1,NaN,-1,2,0,1,30
2,202300000002,3,120,0,NaN,2,3,2,1,-1,-1,1,NaN,-1,2,0,1,50
3,202300000003,3,5,0,NaN,2,4,0,1,1,0,1,NaN,-1,2,5,1,50
4,202300000003,3,87,0,NaN,2,4,0,1,1,0,1,NaN,-1,2,5,1,50
5,202300000004,2,6,0,NaN,2,4,0,1,18,1,1,NaN,12,2,0,1,50
6,202300000005,4,NaN,0,NaN,1,1,0,1,-1,-1,1,NaN,-1,2,0,1,30
7,202300000005,4,NaN,0,NaN,2,2,0,1,-1,-1,1,NaN,-1,2,0,1,30
8,202300000006,4,NaN,0,NaN,1,1,0,1,-1,-1,1,NaN,-1,2,0,1,50
9,202300000007,3,7,0,NaN,2,4,3,1,-1,-1,1,NaN,-1,2,0,1,50
10,202300000008,3,130,0,NaN,3,4,0,1,-1,-1,1,NaN,-1,2,0,1,50
11,202300000008,3,NaN,0,NaN,2,2,0,1,-1,-1,1,NaN,-1,2,0,1,50
12,202300000009,3,5,0,NaN,3,4,0,1,-1,-1,1,NaN,-1,2,5,1,50
13,202300000009,3,87,0,NaN,1,2,0,1,-1,-1,1,NaN,-1,1,5,1,50
14,202300000010,3,231,0,NaN,2,2,0,1,-1,-1,1,NaN,-1,2,0,1,50

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70860 entries, 0 to 70859
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  70860 non-null  int64
 1   catr     70860 non-null  int64
 2   voie     58113 non-null  object
 3   v1       70860 non-null  int64
 4   v2       5884 non-null   object
 5   circ     70860 non-null  int64
 6   nbv      70860 non-null  object
 7   vosp     70860 non-null  int64
 8   prof     70860 non-null  int64
 9   pr       70860 non-null  object
 10  pr1      70860 non-null  object
 11  plan     70860 non-null  int64
 12  lartpc   31 non-null     object
 13  larrout  70860 non-null  object
 14  surf     70860 non-null  int64
 15  infra    70860 non-null  int64
 16  situ     70860 non-null  int64
 17  vma      70860 non-null  int64
dtypes: int64(11), object(7)
memory usage: 9.7+ MB
None

            Num_Acc          catr            v1          circ          vosp  \
count  7.086000e+04  70860.000000  70860.000000  70860.000000  70860.000000
mean   2.023000e+11      3.397403     -0.228860      1.712673      0.183164
std    1.581802e+04      1.113553      0.431536      0.942601      0.744139
min    2.023000e+11      1.000000     -1.000000     -1.000000     -1.000000
25%    2.023000e+11      3.000000      0.000000      1.000000      0.000000
50%    2.023000e+11      3.000000      0.000000      2.000000      0.000000
75%    2.023000e+11      4.000000      0.000000      2.000000      0.000000
max    2.023001e+11      9.000000      3.000000      4.000000      3.000000

               prof         plan          surf         infra          situ  \
count  70860.000000  70860.00000  70860.000000  70860.000000  70860.000000
mean       1.206336      1.26733      1.254036      0.811177      1.611727
std        0.534770      0.65518      0.756575      2.162585      1.627796
min       -1.000000     -1.00000     -1.000000     -1.000000     -1.000000
25%        1.000000      1.00000      1.000000      0.000000      1.000000
50%        1.000000      1.00000      1.000000      0.000000      1.000000
75%        1.000000      1.00000      1.000000      0.000000      1.000000
max        4.000000      4.00000      9.000000      9.000000      8.000000

                vma
count  70860.000000
mean      53.306393
std       26.001154
min       -1.000000
25%       30.000000
50%       50.000000
75%       70.000000
max      130.000000

Num_Acc    54822
catr           8
voie       20063
v1             4
v2            24
circ           5
nbv           15
vosp           5
prof           5
pr           446
pr1         1363
plan           5
lartpc        19
larrout      107
surf          10
infra         11
situ           8
vma           21
dtype: int64

catr
4    32364
3    26732
1     5182
2     4015
7     1852
6      413
9      231
5       71
Name: count, dtype: int64

voie
1                                           476
86                                          446
4                                           369
7                                           345
6                                           320
                                           ...
BOULEVARD D AURELLE DE PALADINES              1
RUE GUSTAVE FLAUBERT                          1
JEAN MOULIN                         (R )      1
RUE CHARLES FOURIER                           1
BAMBOU (CHEMIN DE LA RUELLE)                  1
Name: count, Length: 20063, dtype: int64

circ
 2    43483
 1    14037
 3     7898
-1     5021
 4      421
Name: count, dtype: int64

nbv
2               42580
1                8393
4                6092
3                5105
 -1              4153
0                2080
6                1197
5                 726
8                 292
7                  94
#VALEURMULTI       54
10                 48
9                  23
12                 16
11                  7
Name: count, dtype: int64

surf
 1    55970
 2    13930
 9      296
-1      208
 7      122
 3      114
 8       84
 5       65
 6       49
 4       22
Name: count, dtype: int64

situ
 1    59259
 3     4156
 8     2683
 5     1934
 4     1472
 6      835
 2      323
-1      198
Name: count, dtype: int64

vma
 50     32127
 30     13074
 80      8331
 90      4835
-1       4578
 70      4257
 110     2031
 130     1089
 20       239
 60       121
 25        69
 40        65
 45        15
 100       12
 10         6
 15         4
 75         2
 35         2
 31         1
 65         1
 23         1
Name: count, dtype: int64

### Users

In [45]:
display(usagers_2023.head(20))
print(usagers_2023.info())

# grav = Severity (The Target Variable)
# 1=Uninjured, 2=Killed, 3=Hospitalized, 4=Slightly Injured
print("Severity Distribution (Target):\n", usagers_2023['grav'].value_counts())

# catu = Category of User (1=Driver, 2=Passenger, 3=Pedestrian)
print("User Category:\n", usagers_2023['catu'].value_counts())

# secu1, secu2, secu3 = Safety Equipment (Seatbelt, Helmet)
# This often requires cleaning (values like 11, 21 often mean 'Belt Used', 'Helmet Used')
print("Safety Equipment:\n", usagers_2023['secu1'].value_counts())

,Num_Acc,id_usager,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202300000001,203 851 184,155 680 557,A01,1,1,4,1,1978.0,5,2,0,-1,-1,-1,-1
1,202300000002,203 851 182,155 680 556,A01,1,1,1,2,1997.0,9,1,0,-1,-1,-1,-1
2,202300000002,203 851 183,155 680 556,A01,10,3,3,1,1997.0,9,0,-1,-1,2,3,1
3,202300000003,203 851 180,155 680 554,B01,1,1,3,1,1987.0,0,2,6,0,0,0,-1
4,202300000003,203 851 181,155 680 555,A01,1,1,1,2,1984.0,0,1,0,0,0,0,-1
5,202300000004,203 851 175,155 680 551,B01,2,2,1,2,2001.0,1,1,0,-1,-1,-1,-1
6,202300000004,203 851 176,155 680 551,B01,1,1,1,2,1995.0,1,1,0,-1,-1,-1,-1
7,202300000004,203 851 177,155 680 552,C01,1,1,1,1,1968.0,9,1,0,-1,-1,-1,-1
8,202300000004,203 851 178,155 680 552,C01,2,2,4,1,1956.0,0,1,0,-1,-1,-1,-1
9,202300000004,203 851 179,155 680 553,A01,1,1,1,1,1985.0,1,1,0,-1,-1,-1,-1
10,202300000005,203 851 173,155 680 549,B01,1,1,4,2,2001.0,0,1,0,-1,-1,-1,-1
11,202300000005,203 851 174,155 680 550,A01,1,1,1,1,2001.0,3,1,0,-1,-1,-1,-1
12,202300000006,203 851 171,155 680 548,A01,10,3,4,1,2003.0,9,0,-1,-1,3,3,1
13,202300000006,203 851 172,155 680 548,A01,1,1,1,1,1962.0,5,1,0,-1,-1,-1,-1
14,202300000007,203 851 167,155 680 545,C01,1,1,1,1,1988.0,0,1,0,-1,-1,-1,-1
15,202300000007,203 851 168,155 680 546,A01,4,2,4,2,1975.0,5,1,0,-1,-1,-1,-1
16,202300000007,203 851 169,155 680 546,A01,1,1,1,1,1968.0,5,1,0,-1,-1,-1,-1
17,202300000007,203 851 170,155 680 547,B01,1,1,1,2,1979.0,0,1,0,-1,-1,-1,-1
18,202300000008,203 851 164,155 680 543,B01,4,2,4,2,2020.0,0,1,8,-1,-1,-1,-1
19,202300000008,203 851 165,155 680 543,B01,1,1,1,1,1980.0,0,1,0,-1,-1,-1,-1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125789 entries, 0 to 125788
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      125789 non-null  int64
 1   id_usager    125789 non-null  object
 2   id_vehicule  125789 non-null  object
 3   num_veh      125789 non-null  object
 4   place        125789 non-null  int64
 5   catu         125789 non-null  int64
 6   grav         125789 non-null  int64
 7   sexe         125789 non-null  int64
 8   an_nais      123191 non-null  float64
 9   trajet       125789 non-null  int64
 10  secu1        125789 non-null  int64
 11  secu2        125789 non-null  int64
 12  secu3        125789 non-null  int64
 13  locp         125789 non-null  int64
 14  actp         125789 non-null  object
 15  etatp        125789 non-null  int64
dtypes: float64(1), int64(11), object(4)
memory usage: 15.4+ MB
None
Severity Distribution (Target):
 grav
 1    53399
 4    49603
 3    19271
 2     3398
-1      118
Name: count, dtype: int64
User Category:
 catu
1    93462
2    22806
3     9521
Name: count, dtype: int64
Safety Equipment:
 secu1
 1    72988
 2    22012
 8    15480
 0    11938
-1     2292
 3      726
 6      135
 9      123
 4       67
 5       27
 7        1
Name: count, dtype: int64

### Vehicles

In [32]:
display(vehicules_2023.head())
print(vehicules_2023.info())

,Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc
0,202300000001,155 680 557,A01,1,30,0,0,5,1,1,NaN
1,202300000002,155 680 556,A01,2,7,0,1,1,1,1,NaN
2,202300000003,155 680 554,B01,1,2,0,2,1,16,1,NaN
3,202300000003,155 680 555,A01,2,7,0,2,2,15,1,NaN
4,202300000004,155 680 551,B01,1,7,0,2,9,2,4,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93585 entries, 0 to 93584
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Num_Acc      93585 non-null  int64
 1   id_vehicule  93585 non-null  object
 2   num_veh      93585 non-null  object
 3   senc         93585 non-null  int64
 4   catv         93585 non-null  int64
 5   obs          93585 non-null  int64
 6   obsm         93585 non-null  int64
 7   choc         93585 non-null  int64
 8   manv         93585 non-null  int64
 9   motor        93585 non-null  int64
 10  occutc       838 non-null    float64
dtypes: float64(1), int64(8), object(2)
memory usage: 7.9+ MB
None

In [33]:
# catv = Category of Vehicle
# Common codes: 7=Car, 10=Van, 33=Motorcycle (heavy), 1=Bicycle
print("Vehicle Categories:\n", vehicules_2023['catv'].value_counts())

# obs = Obstacle hit (fixed)
# 0=None, 1=Tree, 2=Pole, etc. useful for severity prediction.
print("Fixed Obstacles Hit:\n", vehicules_2023['obs'].value_counts())

Vehicle Categories:
 catv
 7     54620
 33     7688
 10     6853
 1      5116
 2      3306
 50     2395
 30     2216
 32     1803
 31     1759
 15      935
 34      893
 80      762
 14      716
 37      675
 43      618
 17      543
 3       482
 99      393
 13      376
 0       259
 21      253
 60      250
 36      180
 38      163
 40      110
 16       44
 20       42
 39       39
 42       37
 35       35
 41       21
-1         3
Name: count, dtype: int64
Fixed Obstacles Hit:
 obs
 0     79495
 1      2234
 13     1717
 2      1445
 4      1397
 3      1272
 8      1101
 6      1091
 12      833
 14      708
 15      515
 9       465
 16      439
 7       274
 5       177
 11      152
 10      113
 17      100
-1        57
Name: count, dtype: int64

# Data Exploration 2024

In [37]:
caract_2024 = pd.read_csv("caract-2024.csv",encoding="utf-8",sep=";")
lieux_2024 = pd.read_csv("lieux-2024.csv",encoding="utf-8",sep=";")
usagers_2024 = pd.read_csv("usagers-2024.csv",encoding="utf-8",sep=";")
vehicules_2024 = pd.read_csv("vehicules-2024.csv",encoding="utf-8",sep=";")

## Characteristics

In [38]:
display(caract_2024.head())
print()
print(caract_2024.info())
print()
print(caract_2024.describe())
print()
print(caract_2024.nunique())
print()
print(caract_2024['lum'].value_counts())
print()
print(caract_2024['agg'].value_counts())
print()
print(caract_2024['int'].value_counts())
print()
print(caract_2024['atm'].value_counts())
print()
print(caract_2024['col'].value_counts())

,Num_Acc,jour,mois,an,hrmn,lum,dep,com,agg,int,atm,col,adr,lat,long
0,202400000001,25,3,2024,07:40,2,70,70285,1,1,5,1,D438,"47,56277000","6,75832000"
1,202400000002,20,3,2024,15:05,1,21,21054,2,3,7,6,HOTEL DIEU (RUE DE L'),"47,02109000","4,83755000"
2,202400000003,22,3,2024,19:30,2,15,15012,1,1,1,6,Allée des Tilleuls,"44,90238400","2,49641800"
3,202400000004,24,3,2024,17:50,1,14,14118,2,3,7,3,128 Rue d'Authie,"49,19166000","-0,39851000"
4,202400000005,25,3,2024,19:35,5,13,13106,1,3,2,5,BEDOULE (CHEMIN DE LA),"43,39000000","5,35000000"

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54402 entries, 0 to 54401
Data columns (total 15 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  54402 non-null  int64
 1   jour     54402 non-null  int64
 2   mois     54402 non-null  int64
 3   an       54402 non-null  int64
 4   hrmn     54402 non-null  object
 5   lum      54402 non-null  int64
 6   dep      54402 non-null  object
 7   com      54402 non-null  object
 8   agg      54402 non-null  int64
 9   int      54402 non-null  int64
 10  atm      54402 non-null  int64
 11  col      54402 non-null  int64
 12  adr      52092 non-null  object
 13  lat      54402 non-null  object
 14  long     54402 non-null  object
dtypes: int64(9), object(6)
memory usage: 6.2+ MB
None

            Num_Acc          jour          mois       an           lum  \
count  5.440200e+04  54402.000000  54402.000000  54402.0  54402.000000
mean   2.024000e+11     15.665490      6.615749   2024.0      1.949708
std    1.570465e+04      8.737761      3.361701      0.0      1.488462
min    2.024000e+11      1.000000      1.000000   2024.0      1.000000
25%    2.024000e+11      8.000000      4.000000   2024.0      1.000000
50%    2.024000e+11     16.000000      7.000000   2024.0      1.000000
75%    2.024000e+11     23.000000     10.000000   2024.0      3.000000
max    2.024001e+11     31.000000     12.000000   2024.0      5.000000

                agg           int           atm           col
count  54402.000000  54402.000000  54402.000000  54402.000000
mean       1.625161      2.108195      1.677493      4.018069
std        0.484086      2.042602      1.736956      1.984560
min        1.000000      1.000000      1.000000     -1.000000
25%        1.000000      1.000000      1.000000      3.000000
50%        2.000000      1.000000      1.000000      3.000000
75%        2.000000      2.000000      1.000000      6.000000
max        2.000000      9.000000      9.000000      7.000000

Num_Acc    54402
jour          31
mois          12
an             1
hrmn        1414
lum            5
dep          107
com        11285
agg            2
int            9
atm            9
col            8
adr        28871
lat        52471
long       52742
dtype: int64

lum
1    35580
5     8499
3     6101
2     3599
4      623
Name: count, dtype: int64

agg
2    34010
1    20392
Name: count, dtype: int64

int
1    34589
3     6451
2     6289
6     2717
9     2454
4     1048
7      453
5      263
8      138
Name: count, dtype: int64

atm
1    41802
2     6779
8     2374
3     1449
7      817
5      529
9      250
4      233
6      169
Name: count, dtype: int64

col
 3    16371
 6    15968
 2     7162
 1     6057
 7     5463
 4     1821
 5     1554
-1        6
Name: count, dtype: int64

Lighting conditions at accident time (lum): most of the accidents occurred during daylight (1)
Localisation (Agg): Most accidents occurred in urban areas (2)
Type of Intersection (Int): Most accidents occurred not at intersections (1)
Meteorological factors (atm): Most accidents occurred in normal weather (1)

## Places

In [39]:
display(lieux_2024.head())
print()
print(lieux_2024.info())
print()
print(lieux_2024.describe())
print()
print(lieux_2024.nunique())
print()
print(lieux_2024['catr'].value_counts())
print()
print(lieux_2024['voie'].value_counts())
print()
print(lieux_2024['circ'].value_counts())
print()
print(lieux_2024['nbv'].value_counts())
print()
print(lieux_2024['surf'].value_counts())
print()
print(lieux_2024['situ'].value_counts())
print()
print(lieux_2024['vma'].value_counts())

,Num_Acc,catr,voie,v1,v2,circ,nbv,vosp,prof,pr,pr1,plan,lartpc,larrout,surf,infra,situ,vma
0,202400000001,3,D438,0,NaN,2,2,0,1,1,260,2,NaN,7,1,0,1,90
1,202400000002,4,HOTEL DIEU (RUE DE L'),0,NaN,2,2,0,1,-1,-1,1,NaN,-1,9,0,1,30
2,202400000002,4,POTERNE (RUE),0,NaN,1,1,0,1,-1,-1,1,NaN,-1,9,0,1,30
3,202400000003,4,TILLEULS (ALLEE DES),0,NaN,2,2,0,1,-1,-1,1,NaN,-1,1,0,3,50
4,202400000004,4,AUTHIE (N° 106 PAIRS -115 IMPAIRS),0,NaN,2,4,0,1,-1,-1,1,NaN,-1,1,9,1,50

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70248 entries, 0 to 70247
Data columns (total 18 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Num_Acc  70248 non-null  int64
 1   catr     70248 non-null  int64
 2   voie     56917 non-null  object
 3   v1       70248 non-null  int64
 4   v2       5916 non-null   object
 5   circ     70248 non-null  int64
 6   nbv      70248 non-null  object
 7   vosp     70248 non-null  int64
 8   prof     70248 non-null  int64
 9   pr       70248 non-null  object
 10  pr1      70248 non-null  object
 11  plan     70248 non-null  int64
 12  lartpc   33 non-null     object
 13  larrout  70248 non-null  object
 14  surf     70248 non-null  int64
 15  infra    70248 non-null  int64
 16  situ     70248 non-null  int64
 17  vma      70248 non-null  int64
dtypes: int64(11), object(7)
memory usage: 9.6+ MB
None

            Num_Acc          catr            v1          circ          vosp  \
count  7.024800e+04  70248.000000  70248.000000  70248.000000  70248.000000
mean   2.024000e+11      3.401577     -0.228277      1.735622      0.185870
std    1.570887e+04      1.123805      0.432355      0.908124      0.745757
min    2.024000e+11      1.000000     -1.000000     -1.000000     -1.000000
25%    2.024000e+11      3.000000      0.000000      1.000000      0.000000
50%    2.024000e+11      3.000000      0.000000      2.000000      0.000000
75%    2.024000e+11      4.000000      0.000000      2.000000      0.000000
max    2.024001e+11      9.000000      3.000000      4.000000      3.000000

               prof          plan          surf         infra          situ  \
count  70248.000000  70248.000000  70248.000000  70248.000000  70248.000000
mean       1.215707      1.278029      1.283652      0.847910      1.640132
std        0.527901      0.656011      0.808301      2.201907      1.676732
min       -1.000000     -1.000000     -1.000000     -1.000000     -1.000000
25%        1.000000      1.000000      1.000000      0.000000      1.000000
50%        1.000000      1.000000      1.000000      0.000000      1.000000
75%        1.000000      1.000000      1.000000      0.000000      1.000000
max        4.000000      4.000000      9.000000      9.000000      8.000000

                vma
count  70248.000000
mean      53.711479
std       27.238233
min       -1.000000
25%       30.000000
50%       50.000000
75%       70.000000
max      900.000000

Num_Acc    54402
catr           8
voie       19750
v1             4
v2            27
circ           5
nbv           15
vosp           5
prof           5
pr           461
pr1         1353
plan           5
lartpc        15
larrout       65
surf          10
infra         11
situ           8
vma           36
dtype: int64

catr
4    31977
3    26452
1     5181
2     3968
7     1941
6      441
9      225
5       63
Name: count, dtype: int64

voie
86                       625
1                        619
4                        424
3                        420
2                        309
                        ...
GENOTTES (AVENUE DES)      1
ROULANTS (RUE DES)         1
DARDANELLES (AVE DES)      1
ILES (CORNICHE DES)        1
RUE PIERRE GAUDIN          1
Name: count, Length: 19750, dtype: int64

circ
 2    43402
 1    14195
 3     7909
-1     4354
 4      388
Name: count, dtype: int64

nbv
2               42693
1                8174
4                5488
3                5243
 -1              4178
0                2346
6                1048
5                 651
8                 238
7                  70
#VALEURMULTI       50
10                 36
9                  18
12                 14
11                  1
Name: count, dtype: int64

surf
 1    54953
 2    14257
 9      296
 7      268
 3      125
 5      120
 8       85
 6       63
 4       43
-1       38
Name: count, dtype: int64

situ
 1    58833
 3     3982
 8     2983
 5     1771
 4     1447
 6      895
 2      299
-1       38
Name: count, dtype: int64

vma
 50     31560
 30     13612
 80      8221
 90      5247
 70      4177
-1       3630
 110     1791
 130     1009
 20       301
 10       172
 60       124
 40        96
 15        73
 25        67
 5         43
 500       21
 45        21
 1         21
 100       16
 2         12
 6          9
 3          8
 300        2
 35         2
 900        2
 75         1
 85         1
 95         1
 800        1
 55         1
 140        1
 4          1
 700        1
 0          1
 16         1
 301        1
Name: count, dtype: int64

## Users

In [40]:
display(usagers_2024.head())
print(usagers_2024.info())

# grav = Severity (The Target Variable)
# 1=Uninjured, 2=Killed, 3=Hospitalized, 4=Slightly Injured
print("Severity Distribution (Target):\n", usagers_2024['grav'].value_counts())

# catu = Category of User (1=Driver, 2=Passenger, 3=Pedestrian)
print("User Category:\n", usagers_2024['catu'].value_counts())

# secu1, secu2, secu3 = Safety Equipment (Seatbelt, Helmet)
# This often requires cleaning (values like 11, 21 often mean 'Belt Used', 'Helmet Used')
print("Safety Equipment:\n", usagers_2024['secu1'].value_counts())

,Num_Acc,id_usager,id_vehicule,num_veh,place,catu,grav,sexe,an_nais,trajet,secu1,secu2,secu3,locp,actp,etatp
0,202400000001,203 988 581,155 781 758,A01,1,1,3,1,2003.0,2,1,-1,-1,-1,-1,-1
1,202400000001,203 988 582,155 781 759,B01,1,1,1,1,1997.0,4,1,-1,-1,-1,-1,-1
2,202400000002,203 988 579,155 781 757,A01,10,3,3,2,1927.0,5,0,-1,-1,3,3,1
3,202400000002,203 988 580,155 781 757,A01,1,1,1,1,1987.0,4,1,0,-1,3,3,1
4,202400000003,203 988 574,155 781 756,A01,2,2,4,2,2007.0,5,8,0,-1,-1,-1,-1

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125187 entries, 0 to 125186
Data columns (total 16 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Num_Acc      125187 non-null  int64
 1   id_usager    125187 non-null  object
 2   id_vehicule  125187 non-null  object
 3   num_veh      125187 non-null  object
 4   place        125187 non-null  int64
 5   catu         125187 non-null  int64
 6   grav         125187 non-null  int64
 7   sexe         125187 non-null  int64
 8   an_nais      122608 non-null  float64
 9   trajet       125187 non-null  int64
 10  secu1        125187 non-null  int64
 11  secu2        125187 non-null  int64
 12  secu3        125187 non-null  int64
 13  locp         125187 non-null  int64
 14  actp         125187 non-null  object
 15  etatp        125187 non-null  int64
dtypes: float64(1), int64(11), object(4)
memory usage: 15.3+ MB
None
Severity Distribution (Target):
 grav
1    52920
4    49709
3    19126
2     3432
Name: count, dtype: int64
User Category:
 catu
1    92581
2    23205
3     9401
Name: count, dtype: int64
Safety Equipment:
 secu1
 1    72919
 2    21246
 8    15584
 0    12216
-1     2103
 3      723
 9      139
 6      126
 4      104
 5       25
 7        2
Name: count, dtype: int64

## Vehicles

In [41]:
display(vehicules_2024.head())
print(vehicules_2024.info())

,Num_Acc,id_vehicule,num_veh,senc,catv,obs,obsm,choc,manv,motor,occutc
0,202400000001,155 781 758,A01,1,7,0,2,1,13,1,NaN
1,202400000001,155 781 759,B01,2,14,0,2,2,21,1,NaN
2,202400000002,155 781 757,A01,1,10,0,1,3,15,1,NaN
3,202400000003,155 781 756,A01,3,3,9,1,1,1,1,NaN
4,202400000004,155 781 754,B01,3,34,0,2,0,0,1,NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 92678 entries, 0 to 92677
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Num_Acc      92678 non-null  int64
 1   id_vehicule  92678 non-null  object
 2   num_veh      92678 non-null  object
 3   senc         92678 non-null  int64
 4   catv         92678 non-null  int64
 5   obs          92678 non-null  int64
 6   obsm         92678 non-null  int64
 7   choc         92678 non-null  int64
 8   manv         92678 non-null  int64
 9   motor        92678 non-null  int64
 10  occutc       949 non-null    float64
dtypes: float64(1), int64(8), object(2)
memory usage: 7.8+ MB
None

In [42]:
# catv = Category of Vehicle
# Common codes: 7=Car, 10=Van, 33=Motorcycle (heavy), 1=Bicycle
print("Vehicle Categories:\n", vehicules_2024['catv'].value_counts())

# obs = Obstacle hit (fixed)
# 0=None, 1=Tree, 2=Pole, etc. useful for severity prediction.
print("Fixed Obstacles Hit:\n", vehicules_2024['obs'].value_counts())

Vehicle Categories:
 catv
 7     53911
 33     7777
 10     7062
 1      5045
 2      3090
 50     2867
 30     2036
 32     1714
 31     1609
 15      936
 34      789
 80      781
 37      708
 14      652
 43      559
 17      493
 3       473
 13      380
 99      299
 0       287
 21      270
 60      255
 38      241
 36      165
 40      124
 20       47
 39       31
 16       28
 41       19
 42       17
 35       12
-1         1
Name: count, dtype: int64
Fixed Obstacles Hit:
 obs
 0     78800
 1      2259
 13     1652
 2      1508
 4      1371
 3      1202
 8      1124
 6      1049
 12      818
 14      652
 15      515
 9       492
 16      416
 7       264
 5       190
 11      155
 17       93
 10       91
-1        27
Name: count, dtype: int64